### ISSUE TITLE
都是有孩子的人了，沉稳一些，搞明白了再抱怨吧。

### ISSUE THREAD

**Issue by humyna** [nshen/learn-ArcBlock-in-two-days#2]

**Comment by nshen** [comment]
这还牵扯到我孩子了？

**Comment by humyna** [comment]
你不是在文中矫情说什么周末没法陪孩子吗？但你行文给人的感觉就是刚毕业的大学生，意气用事，我觉得他们没招你挺对的。

**Comment by nshen** [comment]
我还真想是大学生，可惜已经老了， 时间宝贵。我没做出来是我的错，或者哪里做错了你指出来我再改进也行。 一句没通过，我两天就没了，白嫖测bug啊？还不让我抱怨，不抱怨也行，两天工钱你到是给报一下啊。
